Repository Unorthdox-Developers/peek-frontend, pull requests merged in 2021-09, with the labels that each got.

#22 codeql Analysis Sample
  .github/workflows/codeql-analysis.yml
Labels: security

#25 Feature/add cypress
  .gitignore
  cypress.json
  package.json
  src/cypress.env.json
  src/tests/cypress/fixtures/example.json
  src/tests/cypress/integration/searchPage/pageLayout.spec.ts
  src/tests/cypress/plugins/index.js
  src/tests/cypress/support/commands.js
  src/tests/cypress/support/index.js
  src/tests/cypress/support/targets/searchPage.ts
  tsconfig.json
  yarn.lock
Labels: testing

#26 Lighthouse fixes
  package.json
  public/index.css
  public/index.html
  src/App.tsx
  src/components/atoms/Button.tsx
  src/components/atoms/Icon.tsx
  src/components/atoms/Label.tsx
  src/components/atoms/Link.tsx
  src/components/atoms/Loading.tsx
  src/components/atoms/RepositoryCardContent.tsx
  src/components/atoms/Switch.tsx
  src/components/atoms/TextInput.tsx
  src/components/atoms/UnorderedList.tsx
  src/components/molecules/SearchInput.tsx
  src/components/organisms/RepositorySearch.tsx
  src/components/organisms/RepositorySearchResults.tsx
  src/index.tsx
  src/layouts/RepositoryDashboardLayout.tsx
  src/layouts/RepositorySearchLayout.tsx
  src/pages/MainPage.tsx
  src/pages/RepositoryDashboardPage.tsx
  src/pages/RepositorySearchPage.tsx
  src/reportWebVitals.js
  src/styles/theme.ts
  yarn.lock
Labels: frontend
